### PR TITLE
Refactor invoke method (1.4.1 -> 1.5.0) [breaking change]

### PR DESCRIPTION
**Pull request by kiplelive-zariman**

### CODE REVIEW

**Comment by kiplelive-zariman** [comment]
This branch, I revert the merged with zendesk-web branch

**Comment by KohlsAdrian** [comment]
LGTM

Looking at the implementation looks perfectly fine
I'll test it out, and working as expected I will merge this PR

**Comment by KohlsAdrian** [comment]
iOS is not working the changes

**Comment by KohlsAdrian** [comment]
Android passing

iOS having some issue

**Comment by KohlsAdrian** [comment]
For some reason, on iOS sending a message, the message is on PENDING status

**Comment by kiplelive-zariman** [comment]
Not sure with the issue, I didn't touch the code for sending message, will check later

**Comment by KohlsAdrian** [comment]
I spent 3 hours trying to figure it out what should be happening for iOS not working as expected.
Android performance was awesome replacing periodic with invokeMethod and everything working just fine.
Unfortunately iOS was not working as on Android
I hope you can help find a fix too

**Comment by KohlsAdrian** [comment]
I think iOS SDK Chat is offline ou Zendesk having issues with it. When things get back to normal I review it again and merge if it succeeded

**Comment by KohlsAdrian** [comment]
Zendesk is not offline, that's an issue only on iOS that I am having issues to find out

**Comment by diegogarciar** [comment]
Hello, 
@KohlsAdrian Thanks for the package, I was actually going nuts as I thought I was missing some configurations to receive the tickets but it seems it is a known issue to you for iOS, I actually ran pod update to install latest pod (2.11.0) and the issue disappeared. 
As a suggestion  you should specify the pod version in your `ios/zendesk2.podspec` file as below.

```
 s.dependency 'ZendeskChatSDK', '~> 2.11.0'
 s.dependency 'ZendeskChatProvidersSDK', '~>2.11.0'
```
  
The drawback is that you have to keep it up to date, but at least but you won't break production code


Thanks again!

**Comment by KohlsAdrian** [comment]
@diegogarciar that's awesome news! I'll update it as soon as I have free time and test it out, then it it works fine in both platforms I'll merge it out!

**Comment by KohlsAdrian** [comment]
@kiplelive-zariman please update zendesk2.podspec as mentioned above from @diegogarciar so I can review it and merge the fix

**Comment by KohlsAdrian** [comment]
I will manually add de updated dependency, thanks everyone for the help

**Comment by KohlsAdrian** [comment]
Released as 1.5.0 on pub.dev

**Pull request merged**
