### PR TITLE
using methodCallHandler & invokeMethod instead of periodic

### PR DESCRIPTION
**Pull request by kiplelive-zariman**
Hi,

This PR only for suggestion, used methodCallHandler instead of ```Timer.periodic```,  I think this way will make the performance more better.

Or is there any issue, if we use ```invokeMethod``` on native and ```setMethodCallHandler``` on dart?

### CODE REVIEW

**Comment by KohlsAdrian** [comment]
Periodic is not the best way for sure, but it was the fastest thing I could do at the time, I am still learning advanced Crossplatform data manipulation.
Unfortunately, most changes you made makes no sense.
Setting `method` object in every function goes way far from the purpose of the architecture and life cycle of the app

**Comment by KohlsAdrian** [comment]
I have a new branch for flutter web development, it's a long going project, and I will add this optimization for mobile replacing `Timer.periodic`
Will close this as it is way out of the purpose of the architecture and life cycle of the plugin. I appreciate the effort

**Comment by KohlsAdrian** [comment]
No, this snippet seems good, it's the other changes you made that makes no sense

**Comment by kiplelive-zariman** [comment]
> No, this snippet seems good, it's the other changes you made that makes no sense

That part, to invoke method from dart side, I don't think there are another way to trigger/communicate with flutter except ``invokeMethod()```

**Comment by kiplelive-zariman** [comment]
Second  approach

https://github.com/kiplelive-zariman/zendesk2/commit/27cc54bb006492456ed2e9cfee9bc892429225ee

**Comment by KohlsAdrian** [comment]
That looks better, I will review it as soon as I have time

**Comment by KohlsAdrian** [comment]
I have reopened so you can redo the unnecessary changes and pull the refactor code

**Comment by KohlsAdrian** [comment]
I cannot continue with this PR becaused it contains changes from Zendesk-web branch that is not finished, please remove the merge ou create a new PR only with the request context changes, I can't merge unfinished things

**Pull request closed without merging**
